apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: DOCKERHUB_USERNAME/mes-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@db-service.development.svc.cluster.local:5432/mes_db"
            - name: JWT_SECRET
              value: "your-super-secret-key-that-is-long-and-secure"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: development
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort 